<?php
require_once 'config.php';
requireRole('admin');

// Get filter parameters
$status = $_GET['status'] ?? 'all';
$priority = $_GET['priority'] ?? 'all';
$dateFrom = $_GET['date_from'] ?? '';
$dateTo = $_GET['date_to'] ?? '';
$projectId = $_GET['project_id'] ?? 'all';
$developerId = $_GET['developer_id'] ?? 'all';
$testerId = $_GET['tester_id'] ?? 'all';

// Build query
$whereClause = '';
$params = [];

if ($status !== 'all') {
    $whereClause .= " WHERE bt.status = ?";
    $params[] = $status;
}

if ($priority !== 'all') {
    $whereClause .= $whereClause ? " AND bt.priority = ?" : " WHERE bt.priority = ?";
    $params[] = $priority;
}

if (!empty($dateFrom)) {
    $whereClause .= $whereClause ? " AND DATE(bt.created_at) >= ?" : " WHERE DATE(bt.created_at) >= ?";
    $params[] = $dateFrom;
}

if (!empty($dateTo)) {
    $whereClause .= $whereClause ? " AND DATE(bt.created_at) <= ?" : " WHERE DATE(bt.created_at) <= ?";
    $params[] = $dateTo;
}

if ($projectId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.project_id = ?" : " WHERE bt.project_id = ?";
    $params[] = $projectId;
}

if ($developerId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.assigned_dev_id = ?" : " WHERE bt.assigned_dev_id = ?";
    $params[] = $developerId;
}

if ($testerId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.created_by = ?" : " WHERE bt.created_by = ?";
    $params[] = $testerId;
}

// Get projects for filter dropdown
$projects = [];
try {
    $stmt = $pdo->query("SELECT id, name FROM projects ORDER BY name");
    $projects = $stmt->fetchAll();
} catch (PDOException $e) {
    $error = 'Failed to fetch projects: ' . $e->getMessage();
}

// Get developers and testers for filter dropdowns
$developers = [];
$testers = [];
try {
    $stmt = $pdo->query("SELECT id, name FROM users WHERE role = 'developer' ORDER BY name");
    $developers = $stmt->fetchAll();
    $stmt = $pdo->query("SELECT id, name FROM users WHERE role = 'tester' ORDER BY name");
    $testers = $stmt->fetchAll();
} catch (PDOException $e) {
    $error = 'Failed to fetch users: ' . $e->getMessage();
}

// Get selected project name for PDF header
$selectedProjectName = 'All Projects';
if ($projectId !== 'all') {
    foreach ($projects as $project) {
        if ($project['id'] == $projectId) {
            $selectedProjectName = $project['name'];
            break;
        }
    }
}

// Get bugs for report
$bugs = [];
$totalBugs = 0;
$stats = [
    'pending' => 0,
    'in_progress' => 0,
    'fixed' => 0,
    'approved' => 0,
    'rejected' => 0
];

try {
    // Get all bugs with creator, developer, and project names
    $stmt = $pdo->prepare("
        SELECT bt.*, 
               u1.name as developer_name,
               u2.name as creator_name,
               p.name as project_name
        FROM bug_tickets bt 
        LEFT JOIN users u1 ON bt.assigned_dev_id = u1.id 
        LEFT JOIN users u2 ON bt.created_by = u2.id 
        LEFT JOIN projects p ON bt.project_id = p.id 
        $whereClause 
        ORDER BY bt.id ASC
    ");
    $stmt->execute($params);
    $bugs = $stmt->fetchAll();
    $totalBugs = count($bugs);
    
    // Calculate stats
    foreach ($bugs as $bug) {
        if (isset($stats[$bug['status']])) {
            $stats[$bug['status']]++;
        }
    }
} catch (PDOException $e) {
    $error = 'Failed to generate report: ' . $e->getMessage();
}

// Handle CSV generation
if (isset($_GET['download']) && $_GET['download'] == 'csv') {
    // Set headers for CSV download
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="bug_report_' . date('Y-m-d') . '.csv"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');

    // Generate CSV content
    $output = fopen('php://output', 'w');

    // Write summary section
    fputcsv($output, ['BUG TRACKING REPORT']);
    fputcsv($output, ['Project', $selectedProjectName]);
    fputcsv($output, ['Generated by', $_SESSION['user_name'] ?? 'Unknown']);
    fputcsv($output, ['Date', date('F d, Y')]);
    fputcsv($output, []); // Empty row
    fputcsv($output, ['SUMMARY']);
    fputcsv($output, ['Total Bugs', count($bugs)]);
    fputcsv($output, ['Approved', $stats['approved']]);
    fputcsv($output, ['In Progress', $stats['pending'] + $stats['in_progress']]);
    fputcsv($output, ['Rejected', $stats['rejected']]);
    fputcsv($output, []); // Empty row

    // Write bug details header
    fputcsv($output, ['BUG DETAILS']);
    fputcsv($output, [
        'Bug ID', 
        'Date of Creation', 
        'Project',
        'Module', 
        'Submodule', 
        'Developer', 
        'Bug Title', 
        'Bug Description', 
        'Created By', 
        'Bug Priority', 
        'Status', 
        'Updated On'
    ]);

    // Write bug details
    foreach ($bugs as $bug) {
        fputcsv($output, [
            '#' . $bug['id'],
            date('M d, Y', strtotime($bug['created_at'])),
            $bug['project_name'] ?: 'N/A',
            $bug['module'] ?: 'N/A',
            $bug['submodule'] ?: 'N/A',
            $bug['developer_name'] ?: 'Unassigned',
            $bug['title'],
            substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : ''),
            $bug['creator_name'] ?: 'Unknown',
            $bug['priority'],
            ucfirst(str_replace('_', ' ', $bug['status'])),
            date('M d, Y', strtotime($bug['updated_at']))
        ]);
    }

    fclose($output);
    exit();
}

// Handle PDF (HTML) generation
if (isset($_GET['download']) && $_GET['download'] == 'pdf') {
    // Generate HTML content for PDF
    $htmlContent = generatePDFContent($bugs, $stats, $_SESSION['user_name'] ?? 'Unknown', $selectedProjectName);
    
    // Set headers for HTML download (for PDF conversion)
    header('Content-Type: text/html; charset=utf-8');
    header('Content-Disposition: attachment; filename="bug_report_' . date('Y-m-d') . '.html"');
    
    echo $htmlContent;
    exit();
}

function generatePDFContent($bugs, $stats, $userName, $projectName) {
    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Bug Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; margin-bottom: 30px; }
            .stats { display: flex; justify-content: space-around; margin-bottom: 30px; }
            .stat-item { text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 0.75rem; line-height: 1.2; }
            th { background-color: #f2f2f2; }
            .priority-p1 { background-color: #ef4444; }
            .priority-p2 { background-color: #f97316; }
            .priority-p3 { background-color: #eab308; }
            .priority-p4 { background-color: #22c55e; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Bug Tracking Report</h1>
            <p>Project: <?php echo htmlspecialchars($projectName); ?></p>
            <p>Generated by: <?php echo htmlspecialchars($userName); ?></p>
            <p>Date: <?php echo date('F d, Y'); ?></p>
        </div>
        
        <div class="stats">
            <div class="stat-item">
                <h3><?php echo count($bugs); ?></h3>
                <p>Total Bugs</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['approved']; ?></h3>
                <p>Resolved</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['pending'] + $stats['in_progress']; ?></h3>
                <p>In Progress</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['rejected']; ?></h3>
                <p>Rejected</p>
            </div>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Bug ID</th>
                    <th>Date of Creation</th>
                    <th>Project</th>
                    <th>Module</th>
                    <th>Submodule</th>
                    <th>Developer</th>
                    <th>Bug Title</th>
                    <th>Bug Description</th>
                    <th>Created By</th>
                    <th>Bug Priority</th>
                    <th>Status</th>
                    <th>Updated On</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($bugs as $bug): ?>
                <tr class="priority-<?php echo strtolower($bug['priority']); ?>">
                    <td>#<?php echo $bug['id']; ?></td>
                    <td><?php echo date('M d, Y', strtotime($bug['created_at'])); ?></td>
                    <td><?php echo htmlspecialchars($bug['project_name'] ?: 'N/A'); ?></td>
                    <td><?php echo htmlspecialchars($bug['module'] ?: 'N/A'); ?></td>
                    <td><?php echo htmlspecialchars($bug['submodule'] ?: 'N/A'); ?></td>
                    <td><?php echo $bug['developer_name'] ? htmlspecialchars($bug['developer_name']) : 'Unassigned'; ?></td>
                    <td><?php echo htmlspecialchars($bug['title']); ?></td>
                    <td><?php echo htmlspecialchars(substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : '')); ?></td>
                    <td><?php echo $bug['creator_name'] ? htmlspecialchars($bug['creator_name']) : 'Unknown'; ?></td>
                    <td><?php echo $bug['priority']; ?></td>
                    <td><?php echo ucfirst(str_replace('_', ' ', $bug['status'])); ?></td>
                    <td><?php echo date('M d, Y', strtotime($bug['updated_at'])); ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </body>
    </html>
    <?php
    return ob_get_clean();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Report - <?php echo SITE_NAME; ?></title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="app-container">
        <?php include 'includes/navbar.php'; ?>

        <main class="main-content">
            <div class="page-header">
                <h1>System-Wide Bug Report Generator</h1>
                <p>Generate comprehensive reports of all bug tracking activity</p>
            </div>

            <div class="report-container">
                <div class="report-filters">
                    <h3>Report Filters</h3>
                    <form method="GET" class="filter-form">
                        <div class="form-row">
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select id="status" name="status">
                                    <option value="all" <?php echo ($status == 'all') ? 'selected' : ''; ?>>All Status</option>
                                    <option value="pending" <?php echo ($status == 'pending') ? 'selected' : ''; ?>>Pending</option>
                                    <option value="in_progress" <?php echo ($status == 'in_progress') ? 'selected' : ''; ?>>In Progress</option>
                                    <option value="fixed" <?php echo ($status == 'fixed') ? 'selected' : ''; ?>>Fixed</option>
                                    <option value="approved" <?php echo ($status == 'approved') ? 'selected' : ''; ?>>Approved</option>
                                    <option value="rejected" <?php echo ($status == 'rejected') ? 'selected' : ''; ?>>Rejected</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <select id="priority" name="priority">
                                    <option value="all" <?php echo ($priority == 'all') ? 'selected' : ''; ?>>All Priorities</option>
                                    <option value="P1" <?php echo ($priority == 'P1') ? 'selected' : ''; ?>>P1 - Critical</option>
                                    <option value="P2" <?php echo ($priority == 'P2') ? 'selected' : ''; ?>>P2 - High</option>
                                    <option value="P3" <?php echo ($priority == 'P3') ? 'selected' : ''; ?>>P3 - Medium</option>
                                    <option value="P4" <?php echo ($priority == 'P4') ? 'selected' : ''; ?>>P4 - Low</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="project_id">Project</label>
                                <select id="project_id" name="project_id">
                                    <option value="all" <?php echo ($projectId == 'all') ? 'selected' : ''; ?>>All Projects</option>
                                    <?php foreach ($projects as $project): ?>
                                        <option value="<?php echo $project['id']; ?>" <?php echo ($projectId == $project['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($project['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="developer_id">Developer</label>
                                <select id="developer_id" name="developer_id">
                                    <option value="all" <?php echo ($developerId == 'all') ? 'selected' : ''; ?>>All Developers</option>
                                    <?php foreach ($developers as $developer): ?>
                                        <option value="<?php echo $developer['id']; ?>" <?php echo ($developerId == $developer['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($developer['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="tester_id">Tester</label>
                                <select id="tester_id" name="tester_id">
                                    <option value="all" <?php echo ($testerId == 'all') ? 'selected' : ''; ?>>All Testers</option>
                                    <?php foreach ($testers as $tester): ?>
                                        <option value="<?php echo $tester['id']; ?>" <?php echo ($testerId == $tester['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($tester['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="date_from">From Date</label>
                                <input type="date" id="date_from" name="date_from" value="<?php echo htmlspecialchars($dateFrom); ?>">
                            </div>

                            <div class="form-group">
                                <label for="date_to">To Date</label>
                                <input type="date" id="date_to" name="date_to" value="<?php echo htmlspecialchars($dateTo); ?>">
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">
                                <span>🔍</span> Generate Report
                            </button>
                            <button type="button" onclick="clearFilters()" class="btn btn-outline">Clear Filters</button>
                        </div>
                    </form>
                </div>

                <?php if (isset($error)): ?>
                    <div class="error-message">
                        <p><?php echo htmlspecialchars($error); ?></p>
                    </div>
                <?php elseif (!empty($bugs)): ?>
                    <div class="report-summary">
                        <h3>Report Summary</h3>
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-icon">📊</div>
                                <div class="stat-content">
                                    <h3><?php echo $totalBugs; ?></h3>
                                    <p>Total Bugs</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">⏳</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['pending'] + $stats['in_progress']; ?></h3>
                                    <p>In Progress</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">✅</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['approved']; ?></h3>
                                    <p>Resolved</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">❌</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['rejected']; ?></h3>
                                    <p>Rejected</p>
                                </div>
                            </div>
                        </div>

                        <div class="report-actions">
                            <a href="?<?php echo http_build_query(array_merge($_GET, ['download' => 'pdf'])); ?>" class="btn btn-primary">
                                <span>📄</span> Download PDF Report
                            </a>
                            <a href="?<?php echo http_build_query(array_merge($_GET, ['download' => 'csv'])); ?>" class="btn btn-primary">
                                <span>📊</span> Download CSV Report
                            </a>
                            <button onclick="window.print()" class="btn btn-outline">
                                <span>🖨️</span> Print Report
                            </button>
                        </div>
                    </div>

                    <div class="report-table">
                        <h3>Bug Details</h3>
                        <div class="table-container">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Bug ID</th>
                                        <th>Date of Creation</th>
                                        <th>Project</th>
                                        <th>Module</th>
                                        <th>Submodule</th>
                                        <th>Developer</th>
                                        <th>Bug Title</th>
                                        <th>Bug Description</th>
                                        <th>Created By</th>
                                        <th>Bug Priority</th>
                                        <th>Status</th>
                                        <th>Updated On</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($bugs as $bug): ?>
                                        <tr>
                                            <td>#<?php echo $bug['id']; ?></td>
                                            <td><?php echo date('M d, Y', strtotime($bug['created_at'])); ?></td>
                                            <td><?php echo htmlspecialchars($bug['project_name'] ?: 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($bug['module'] ?: 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($bug['submodule'] ?: 'N/A'); ?></td>
                                            <td><?php echo $bug['developer_name'] ? htmlspecialchars($bug['developer_name']) : 'Unassigned'; ?></td>
                                            <td><?php echo htmlspecialchars($bug['title']); ?></td>
                                            <td><?php echo htmlspecialchars(substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : '')); ?></td>
                                            <td><?php echo $bug['creator_name'] ? htmlspecialchars($bug['creator_name']) : 'Unknown'; ?></td>
                                            <td>
                                                <span class="priority-badge" style="background-color: <?php echo getPriorityColor($bug['priority']); ?>">
                                                    <?php echo $bug['priority']; ?>
                                                </span>
                                            </td>
                                            <td>
                                                <span class="status-badge" style="background-color: <?php echo getStatusColor($bug['status']); ?>">
                                                    <?php echo ucfirst(str_replace('_', ' ', $bug['status'])); ?>
                                                </span>
                                            </td>
                                            <td><?php echo date('M d, Y', strtotime($bug['updated_at'])); ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="empty-state">
                        <div class="empty-icon">📊</div>
                        <h3>No bugs found</h3>
                        <p>No bugs match your current filter criteria. Try adjusting the filters above.</p>
                    </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script>
        function clearFilters() {
            window.location.href = 'generate_report.php';
        }
    </script>

    <style>
        :root {
            --surface-color: #ffffff;
            --border-color: #ddd;
            --background-color: #f2f2f2;
            --text-primary: #333;
            --text-secondary: #666;
            --border-radius: 8px;
            --box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .report-container {
            display: grid;
            gap: 2rem;
        }

        .report-filters {
            background: var(--surface-color, #ffffff);
            padding: 2rem;
            border-radius: var(--border-radius, 8px);
            box-shadow: var(--box-shadow, 0 2px 4px rgba(0, 0, 0, 0.1));
        }

        .report-filters h3 {
            margin-bottom: 1.5rem;
            color: var(--text-primary, #333);
        }

        .filter-form {
            display: grid;
            gap: 1rem;
        }

        .form-row {
            display: flex;
            gap: 1rem;
            flex-wrap: wrap;
        }

        .form-group {
            flex: 1;
            min-width: 200px;
        }

        .report-summary {
            background: var(--surface-color, #ffffff);
            padding: 2rem;
            border-radius: var(--border-radius, 8px);
            box-shadow: var(--box-shadow, 0 2px 4px rgba(0, 0, 0, 0.1));
        }

        .report-summary h3 {
            margin-bottom: 1.5rem;
            color: var(--text-primary, #333);
        }

        .report-actions {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
        }

        .report-table {
            background: var(--surface-color, #ffffff);
            padding: 2rem;
            border-radius: var(--border-radius, 8px);
            box-shadow: var(--box-shadow, 0 2px 4px rgba(0, 0, 0, 0.1));
        }

        .report-table h3 {
            margin-bottom: 1.5rem;
            color: var(--text-primary, #333);
        }

        .table-container {
            overflow-x: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        th, td {
            padding: 0.4rem;
            text-align: left;
            border-bottom: 1px solid var(--border-color, #ddd);
            word-wrap: break-word;
            overflow-wrap: break-word;
            font-size: 0.75rem;
            line-height: 1.1;
        }

        th {
            background: var(--background-color, #f2f2f2);
            font-weight: 600;
            color: var(--text-primary, #333);
            min-width: 80px;
        }

        td {
            color: var(--text-secondary, #666);
            min-width: 80px;
            max-width: 200px;
        }

        th:nth-child(1), td:nth-child(1) { width: 5%; }
        th:nth-child(2), td:nth-child(2) { width: 8%; }
        th:nth-child(3), td:nth-child(3) { width: 10%; }
        th:nth-child(4), td:nth-child(4) { width: 8%; }
        th:nth-child(5), td:nth-child(5) { width: 8%; }
        th:nth-child(6), td:nth-child(6) { width: 10%; }
        th:nth-child(7), td:nth-child(7) { width: 12%; }
        th:nth-child(8), td:nth-child(8) { width: 15%; }
        th:nth-child(9), td:nth-child(9) { width: 8%; }
        th:nth-child(10), td:nth-child(10) { width: 7%; }
        th:nth-child(11), td:nth-child(11) { width: 7%; }
        th:nth-child(12), td:nth-child(12) { width: 8%; }

        .btn-small {
            padding: 0.25rem 0.75rem;
            font-size: 0.7rem;
        }

        .priority-badge, .status-badge {
            display: inline-block;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            color: #fff;
            font-weight: bold;
            font-size: 0.7rem;
        }

        @media print {
            .navbar, .page-header, .report-filters, .report-actions {
                display: none;
            }
            
            .main-content {
                padding: 0;
                max-width: none;
            }
        }

        @media (max-width: 768px) {
            .report-actions {
                flex-direction: column;
            }
            
            table {
                font-size: 0.65rem;
            }
            
            th, td {
                padding: 0.3rem;
            }
            
            th:nth-child(8), td:nth-child(8) { width: 12%; }
            th:nth-child(7), td:nth-child(7) { width: 10%; }
            th:nth-child(3), td:nth-child(3) { width: 8%; }
        }
    </style>
</body>
</html>